#+TITLE: dotfiles

My personal dotfiles

* TL;DR

Run this in the terminal. It will setup homebrew and emacs and install dependencies for you.

#+begin_src shell
./setup.sh
#+end_src

* TODO setup
- [ ] Setup https://gitlab.com/mtekman/org-tanglesync.el for diffing on tangling
- +[ ] change from gnu stow to nix home_manager+
- [ ] templatize git config using nix
- [ ] implement command pallet for hammerspoon
- [X] precompile fennel code in hammerspoon
- [ ] implement git based plugin fetching in hammerspoon
- [ ] create proper repl for hammerspoon-fennel
- [ ] create a kanata flake and add its config and autostart on startup
- [X] replace asdf with mise
- [X] replace alacritty and zellij with wezterm

* TODO backups
** zplug packages

#+begin_quote
───────┬──────────────────────────────────────────────────────────────────────────────────────────────
       │ File: .zplug.tmp/packages.zsh
───────┼──────────────────────────────────────────────────────────────────────────────────────────────
   1   │ zplug "zsh-users/zsh-autosuggestions"
   2   │ zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme
   3   │ zplug "plugins/gitfast", from:oh-my-zsh
   4   │ zplug "plugins/httpie", from:oh-my-zsh
   5   │ zplug "plugins/lol", from:oh-my-zsh
   6   │ zplug "plugins/git-extras", from:oh-my-zsh
   7   │ zplug "plugins/osx", from:oh-my-zsh
   8   │ zplug "plugins/gitignore", from:oh-my-zsh
   9   │ zplug "plugins/github", from:oh-my-zsh
  10   │ zplug "plugins/docker", from:oh-my-zsh
  11   │ zplug "plugins/z", from:oh-my-zsh
  12   │ zplug "plugins/fasd", from:oh-my-zsh
  13   │ zplug "plugins/vi-mode", from:oh-my-zsh
  14   │ zplug "plugins/tmux", from:oh-my-zsh
  15   │ zplug "plugins/kubectl", from:oh-my-zsh
  16   │ zplug "plugins/colored-man-pages", from:oh-my-zsh
  17   │ zplug "zsh-users/zsh-syntax-highlighting", defer:2
  18   │ zplug "plugins/history-substring-search", from:oh-my-zsh, defer:2
  19   │ # zplug "b4b4r07/enhancd", use:init.sh
  20   │ # zplug "denysdovhan/spaceship-prompt", use:spaceship.zsh, as:theme
  21   │ zplug "zpm-zsh/colors"
  22   │ zplug "zdharma/zsh-diff-so-fancy", as:command, use:bin/git-dsf
  23   │ zplug "wfxr/forgit", defer:1
  24   │ zplug "leophys/zsh-plugin-fzf-finder"
  25   │ zplug "aperezdc/zsh-fzy"
  26   │ zplug "oldratlee/hacker-quotes"
  27   │ zplug "zsh-users/zaw", use:zaw.zsh
  28   │ zplug "scmbreeze/scm_breeze"
  29   │ zplug "psprint/zsh-navigation-tools"
───────┴──────────────────────────────────────────────────────────────────────────────────────────────
#+end_quote

** intellimacs

https://github.com/MarcoIeni/intellimacs

** spacevim

#+begin_quote
#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================


# All SpaceVim option below [option] section
[options]
# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme
# layer
colorscheme = "moonlight"
colorscheme_bg = "dark"
# Disable guicolors in basic mode, many terminal do not support 24bit
# true colors
enable_guicolors = true
# Disable statusline separator, if you want to use other value, please
# install nerd fonts
statusline_separator = "arrow"
statusline_inactive_separator = "arrow"
buffer_index_type = 4
enable_tabline_filetype_icon = true
enable_statusline_mode = false
# autocomplete_method = "coc"
enable_neomake = false
enable_ale = true
lint_on_the_fly = true
bootstrap_before = "myspacevim#before"
bootstrap_after = "myspacevim#after"
filemanager = "nerdtree"
enable_vimfiler_welcome = false
enable_vimfiler_gitstatus = true
disabled_plugins = ["vim-signify"]
lsp_engine = "coc"

[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"
# [layers.override_cmd]
# ruby = ['solargraph', 'stdio']
# typescript = ['typescript-language-server', '--stdio']

[[layers]]
name = "checkers"

# [[layers]]
# name = 'colorscheme'

# [[layers]]
# name = 'denite'

# [[layers]]
# name = "leaderf"

# [[layers]]
# name = "unite"

[[layers]]
name = "fzf"

[[layers]]
name = 'edit'
textobj = ['indent', 'line', 'entire']

[[layers]]
name = 'git'
git-plugin = 'gina'

[[layers]]
name = 'lang#dockerfile'

[[layers]]
name = 'lang#elixir'

[[layers]]
name = 'lang#graphql'

[[layers]]
name = 'lang#html'

[[layers]]
name = 'lang#javascript'

[[layers]]
name = 'lang#markdown'

[[layers]]
name = "lang#python"

[[layers]]
name = 'lang#ruby'
repl_command = "pry"

# [[layers]]
# name = 'lang#typescript'

[[layers]]
  name = "lang#typescript"

[[layers]]
name = 'lsp'
filetypes = [ "javascript", "typescript", "css" ]

[[layers]]
name = 'shell'
default_position = 'float'
default_height = 30

[[layers]]
name = 'sudo'

[[layers]]
name = 'tmux'

[[layers]]
name = 'VersionControl'

[[custom_plugins]]
name = "tpope/vim-vinegar"

[[custom_plugins]]
name = "mhartington/oceanic-next"

[[custom_plugins]]
name = "fenetikm/falcon"

[[custom_plugins]]
name = "airblade/vim-gitgutter"

[[custom_plugins]]
name = "jsfaint/coc-neoinclude"

[[custom_plugins]]
name = "neoclide/coc-sources"

[[custom_plugins]]
name = "tpope/vim-obsession"

[[custom_plugins]]
name = "tpope/vim-projectionist"

[[custom_plugins]]
name = "mgedmin/python-imports.vim"

[[custom_plugins]]
name = "ludovicchabant/vim-gutentags"

[[custom_plugins]]
name = "leafgarland/typescript-vim"

[[custom_plugins]]
name = "peitalin/vim-jsx-typescript"

[[custom_plugins]]
name = "mbbill/undotree"

[[custom_plugins]]
name = "Olical/aniseed"

[[custom_plugins]]
name = "Olical/nvim-local-fennel"

[[custom_plugins]]
name = "bakpakin/fennel.vim"

[[custom_plugins]]
name = "Olical/conjure"

[[custom_plugins]]
name = "eraserhd/parinfer-rust"

[[custom_plugins]]
name = "NoahTheDuke/vim-just"

[[custom_plugins]]
name = "dracula/vim"

[[custom_plugins]]
name = "shaunsingh/moonlight.nvim"

#+end_quote

** tmux

#+begin_quote
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-online-status'
set -g @plugin 'tmux-plugins/tmux-net-speed'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'arcticicestudio/nord-tmux'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'

set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-save-shell-history 'on'
set -g @continuum-restore 'on'

# Ring the bell if any background window rang a bell
set -g @plugin 'arcticicestudio/nord-tmux'

# Default termtype. If the rcfile sets $TERM, that overrides this value.
set -g default-terminal screen-256color

# Keep your finger on ctrl, or don't
bind-key ^D detach-client

# Create splits and vertical splits
bind-key v split-window -h
bind-key ^V split-window -h
bind-key s split-window
bind-key ^S split-window

# easily toggle synchronization (mnemonic: e is for echo)
# sends input to all panes in a given window.
bind e setw synchronize-panes on
bind E setw synchronize-panes off

# set first window to index 1 (not 0) to map more to the keyboard layout...
set-option -g base-index 1
set-window-option -g pane-base-index 1

set-option -g mouse on

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'

#+end_quote

** vscode brew bundle
#+begin_quote
vscode "aaron-bond.better-comments"
vscode "ahmadawais.shades-of-purple"
vscode "alefragnani.project-manager"
vscode "andrsdc.base16-themes"
vscode "arcticicestudio.nord-visual-studio-code"
vscode "asf.apache-netbeans-java"
vscode "betterthantomorrow.calva"
vscode "betterthantomorrow.calva-spritz"
vscode "bodil.file-browser"
vscode "bradlc.vscode-tailwindcss"
vscode "catppuccin.catppuccin-vsc"
vscode "christian-kohler.npm-intellisense"
vscode "christian-kohler.path-intellisense"
vscode "codezombiech.gitignore"
vscode "dbaeumer.vscode-eslint"
vscode "dendron.dendron"
vscode "dendron.dendron-markdown-shortcuts"
vscode "dendron.dendron-paste-image"
vscode "denoland.vscode-deno"
vscode "dgileadi.java-decompiler"
vscode "donjayamanne.git-extension-pack"
vscode "donjayamanne.githistory"
vscode "dracula-theme.theme-dracula"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "eliverlara.andromeda"
vscode "enkia.tokyo-night"
vscode "esbenp.prettier-vscode"
vscode "file-icons.file-icons"
vscode "foam.foam-vscode"
vscode "formulahendry.auto-close-tag"
vscode "formulahendry.auto-complete-tag"
vscode "formulahendry.auto-rename-tag"
vscode "georgewfraser.vscode-javac"
vscode "google.geminicodeassist"
vscode "googlecloudtools.cloudcode"
vscode "grafana.vscode-jsonnet"
vscode "grain-lang.vscode-grain"
vscode "graphql.vscode-graphql"
vscode "graphql.vscode-graphql-syntax"
vscode "hpi-swa.polyglot-live-programming"
vscode "humao.rest-client"
vscode "ithildir.java-properties"
vscode "jacobdufault.fuzzy-search"
vscode "james-yu.latex-workshop"
vscode "jeusto.warm-up-typing-test"
vscode "joseffriedrich.luatex"
vscode "justjavac.vscode-deno-extensionpack"
vscode "kahole.magit"
vscode "laurencebahiirwa.deno-std-lib-snippets"
vscode "mathematic.vscode-latex"
vscode "mhutchie.git-graph"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-docker"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vsliveshare.vsliveshare"
vscode "naumovs.theme-oceanicnext"
vscode "oderwat.indent-rainbow"
vscode "oracle-labs-graalvm.gcn"
vscode "oracle-labs-graalvm.gcn-database-drivers"
vscode "oracle-labs-graalvm.graal-cloud-native-pack"
vscode "oracle-labs-graalvm.graalvm"
vscode "oracle-labs-graalvm.graalvm-pack"
vscode "oracle-labs-graalvm.micronaut"
vscode "oracle-labs-graalvm.micronaut-tools"
vscode "oracle-labs-graalvm.oci-devops"
vscode "piotrpalarz.vscode-gitignore-generator"
vscode "pkief.material-icon-theme"
vscode "rafaelmaiolla.diff"
vscode "redhat.java"
vscode "redhat.vscode-yaml"
vscode "robbowen.synthwave-vscode"
vscode "rokoroku.vscode-theme-darcula"
vscode "rvest.vs-code-prettier-eslint"
vscode "shopify.ruby-lsp"
vscode "stateful.runme"
vscode "stringham.copy-with-imports"
vscode "sumneko.lua"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vivaxy.vscode-conventional-commits"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "vscode-org-mode.org-mode"
vscode "vscodevim.vim"
vscode "vspacecode.vspacecode"
vscode "vspacecode.whichkey"
vscode "whizkydee.material-palenight-theme"
vscode "yoavbls.pretty-ts-errors"
vscode "zainchen.json"
vscode "zhuangtongfa.material-theme"
vscode "ziglang.vscode-zig"
vscode "ziyasal.vscode-open-in-github"
#+end_quote
