{ pkgs, inputs, system, ... }:
{
  environment.systemPackages = with pkgs; [
    babashka
    bash
    bat
    # blurred ; dim background apps windows
    bottom
    cloc
    coconutbattery
    coreutils-full
    cowsay
    curlie
    delta
    direnv
    docker-compose
    duckdb
    dust
    # eza # better ls. disabled: no need
    fd
    fzf
    git
    git-fame
    git-hub
    git-lfs
    google-cloud-sql-proxy
    grpcurl
    helix
    hyperfine
    imagemagick
    ispell
    itsycal
    jj-fzf
    jq
    jujutsu
    kanata
    lazygit
    logseq
    luarocks
    mise
    neovim
    nil
    nixd
    nixfmt-rfc-style
    obsidian
    procs
    qmk
    # raycast # disabled since it's too old
    ripgrep
    rlwrap
    stow
    tinymist
    typst
    vim
    yabai
    yt-dlp
    zed-editor
    inputs.hammerspoon.packages.${system}.default
  ];
}
